[package]
name = "osquery"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true
description = "Safe API for an in-process embedded osquery runtime"

[dependencies]
osquery-sys = { workspace = true }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
